  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[main]]
  name = "Portfolio"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[main]]
  name = "Accomplishments"
  weight = 400
  identifier = "accomplishments"

  [[main]]
  name = "Awards"
  weight = 410
  identifier = "awards"
  url = "/awards/"
  parent = "accomplishments"  

  [[main]]
  name = "Certifications"
  weight = 420
  identifier = "certifications"
  url = "/certifications/"
  parent = "accomplishments"
  
  [[main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  [[main]]
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"