  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"
  
  [[main]]
  name = "CV"
  weight = 406
  identifier = "about"
  url = "/CV/"

  [[main]]
  name = "Awards"
  weight = 202
  identifier = "awards"
  url = "/awards/"

  