  [[main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

#  [[main]]
#  name = "Demo App"
#  weight = 304
#  identifier = "demo-app"
#  url = "/demo-app/"
  
  [[main]]
  name = "About"
  weight = 406
  identifier = "about"
  url = "/about/"


  [[main]]
  name = "Awards"
  weight = 202
  identifier = "awards"
  url = "/awards/"

  