[params]
displayMode = "dark"
contentratio = 0.7

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules"
    target = "static/node_modules"

  [[module.mounts]]
    source = "favicon"
    target = "static"

[build]
  writeStats = true
