[params]
displayMode = "dark"
contentratio = 0.7

[module]

  [[module.mounts]]
    source = "static"
    target = "static"

  [[module.mounts]]
    source = "node_modules"
    target = "static/node_modules"

  [[module.mounts]]
    source = "lichess-pgn-viewer"
    target = "static/node_modules/lichess-pgn-viewer"

  [[module.mounts]]
    source = "favicon"
    target = "static"

  [[hugoVersion]]
    extended = true

[build]
  writeStats = true
