rm(list=ls())
#library(renv)
renv::init()
renv::activate()

install.packages(c("tidyverse", "dbplyr", "RPostgres", "DBI", "collapse", 
                   "dadjoke", "ggiraphExtra", "gtsummary", "ggstatsplot", 
                   "ggthemes", "viridis", "dlookr", "rmarkdown"))


library(tidyverse)
library(dbplyr)
library(RPostgres)
library(DBI)
library(dlookr)
library(collapse)
library(dadjoke)
library(ggiraphExtra)
library(gtsummary)
library(ggstatsplot)
library(ggthemes)
library(viridis)

renv::snapshot()

con <- DBI::dbConnect(RPostgres::Postgres(),    
                      host = "localhost",   
                      port = 5432,   
                      dbname = "test",  
                      user = "JoeH",
                      password = "a" )
dbListTables(con)

meta <- tbl(con, "metadata")
game <- tbl(con, "game_data")
white <- tbl(con, "white_data")
black <- tbl(con, "black_data")

glimpse(meta)
# note that the . syntax for passing in the argument is a magrittr thing
# If I used |> pipe (native to R 4.1.0), I wouldn't have this requirement
# since using enviornment and tidyverse is essentially core R at this point
# I'm not too concerned
meta %>% 
    select(termination) %>% 
    as.data.frame(.) %>% 
    tbl_summary(.)

meta %>% 
    filter(termination == "Rules infraction") %>%
    glimpse()



g <- meta %>% 
    filter(rapid == TRUE & classical == TRUE) %>% 
    select(site) %>% 
    as.data.frame()
g



meta_names <- meta %>%
  colnames()
meta_names

game_names <- game %>% 
    colnames()
game_names



left_join <- white %>% 
    left_join(black, by = "game_id")

test <- left_join %>% 
    filter(game_id == 1) %>% 
    glimpse()

white %>% 
    inner_join(black, by = c("game_id")) %>% 
    filter(game_id == 1) %>% 
    glimpse()


white %>% 
    filter(game_id == 1) %>% 
    union_all(black) %>% 
    glimpse()


game %>% 
    filter(has_evals == TRUE) %>% 
    as.data.frame() %>% 
    tbl_summary(type = list(c(game_id) ~ "categorical"))

meta_names

g = game %>% 
    left_join(meta, by="game_id") %>% 
    filter(has_evals == TRUE & has_annotations == FALSE) %>% 
    as.data.frame()

g

# there are some bot v bot games

meta %>% 
    filter(time_control < 1500) %>%
    ggplot(aes(x=time_control/60)) +
  geom_histogram(bins = 100) +
    theme_bw()


meta %>% 
    filter(time_control < 1500) %>%
    ggplot(aes(x=white_elo)) +
    geom_histogram(bins = 100) +
    theme_bw()

meta %>%
    ggplot(aes(x=blitz)) +
    geom_bar(position = "stack") + 
    theme_bw()

meta %>%
    filter(correspond == "TRUE") %>%
    count()

##  mutate to create a new column that has time control ##

df_eval <- game %>%
    select(has_evals) %>%
    group_by(has_evals) %>%
    as.data.frame()

df_eval %>%
    tbl_summary() %>%
    modify_footnote(update = everything() ~ NA)

ggpiestats(
    data = df_eval,
    x = has_evals,
    title = "Games with evaluation",
    caption = "lichess.org",
    package = "ggsci",
    palette = "default_jama",
    legend.title = "Has Evaluation?"
)





ecom2 %>% 
    dbplot::dbplot_bar(device) + ggplot2::xlab("Device") + 
    ggplot2::ylab("Count") + ggplot2::ggtitle("Device Distribution")

## ----line plot-----------------------------------------------------------
ecom2 %>% 
    dbplot::dbplot_line(n_visit) + ggplot2::xlab("Visits") + ggplot2::ylab("Count") 

## ----simple regression---------------------------------------------------
ecom2 %>% 
    dplyr::select(duration, n_visit) %>% 
    modeldb::linear_regression_db(duration)

## ----multiple regression-------------------------------------------------
ecom2 %>% 
    dplyr::select(duration, n_visit, n_pages) %>%
    modeldb::linear_regression_db(duration)

## ----categorical variables-----------------------------------------------
ecom2 %>% 
    dplyr::select(duration, device) %>%
    modeldb::add_dummy_variables(device, values = c("laptop", "mobile", "tablet")) %>%
    modeldb::linear_regression_db(duration)

## ----full example--------------------------------------------------------
ecom2 %>% 
    dplyr::select(duration, n_visit, n_pages, device) %>%
    modeldb::add_dummy_variables(device, values = c("laptop", "mobile", "tablet")) %>%
    modeldb::linear_regression_db(duration, auto_count = TRUE)

## ----linear model--------------------------------------------------------
model <- lm(duration ~ device + referrer + n_visit + n_pages, data = ecom2)
model

## ----add fitted values in a new column-----------------------------------
ecom2 %>% 
    tidypredict::tidypredict_to_column(model) %>% 
    dplyr::select(duration, fit)

## ----tidy eval formula-------------------------------
tidypredict::tidypredict_fit(model)

## ----use R code generated by tidypredict_fit to calculate fitted values--
ecom2 %>%
    dplyr::mutate(
        fit = 441.450192491919 + (ifelse(device == "mobile", 1, 0) *
                                      -30.9522074131866) + (ifelse(device == "tablet", 1,
                                                                   0) * -14.4972018107797) + (ifelse(referrer == "direct",
                                                                                                     1, 0) * -8.98035001912995) + (ifelse(referrer == "google",
                                                                                                                                          1, 0) * -10.038005625893) + (ifelse(referrer == "social",
                                                                                                                                                                              1, 0) * -19.8411767075006) + (ifelse(referrer == "yahoo",
                                                                                                                                                                                                                   1, 0) * -32.0969778768984) + (n_visit * -1.4325653130794) +
            (n_pages * -8.29825840984566)
    ) %>%
    dplyr::select(duration, fit)

## ----sql translation of above step---------------------------------------
tidypredict::tidypredict_sql(model, con)

## ----disconnect----------------------------------------------------------
DBI::dbDisconnect(con)










set.seed(8)
cols <- grDevices::rainbow(50)
canvas_smoke(colors=cols)

dadjoke()
